---
- name: Install Apache on target servers
  hosts: localhost
  become: yes
  become_method: sudo

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes
