---
- name: Installer et démarrer Nginx
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer nginx
      apt:
        name: nginx
        state: present

    - name: S'assurer que nginx est en marche
      service:
        name: nginx
        state: started
        enabled: yes
