---
- name: Install Apache on target servers
  hosts: localhost
  become: true
  become_user: root

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present
